# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release module 1

on:
  push:
    branches: [ main ]
    paths:
      - 'module1/**'
      - 'module2/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          git diff --quiet HEAD -- module1 || echo changed------
          echo $EVENT_CONTEXT
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "pareeksumit101@gmail.com"
          git config user.name "sumitpareek1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dorny/paths-filter@v2
        id: changes1
        with:
          filters: |
            src:
              - 'module1/**'
        # run only if some file in 'src' folder was changed
      - if: steps.changes1.outputs.src == 'true'
        run: |
          git pull
          cd module1
          mvn -B package --file pom.xml
          mvn -B release:prepare release:perform
      - uses: dorny/paths-filter@v2
        id: changes2
        with:
          filters: |
            src:
              - 'module2/**'

        # run only if some file in 'src' folder was changed
      - if: steps.changes2.outputs.src == 'true'
        run: |
          git pull
          cd module2
          mvn -B package --file pom.xml
          mvn -B release:prepare release:perform