# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release module 1

on:
  push:
    branches: [ main ]
    paths:
      - 'module1/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure Git user
      run: |
        git config user.email "pareeksumit101@gmail.com"
        git config user.name "sumitpareek1"
    - name: Publish JAR
      run: |
        cd module1
        mvn -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
