# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release module 1

on:
  push:
    branches: [ main ]
    paths:
      - 'module1/**'
      env:
        module1: 'present'
      - 'module2/**'
      env:
        module2: 'present'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run:  |
          git pull
          cd module1
          mvn -B package --file pom.xml
      - name: Configure Git user
        run: |
          git config user.email "pareeksumit101@gmail.com"
          git config user.name "sumitpareek1"
      - name: Publish JAR module 1
        if: module1 == 'present'
        run: |
          if: module1 == 'present'
          cd module1
          mvn -B release:prepare release:perform
      - name: Publish JAR module 2
        if: module2 == 'present'
        run: |
          if: module2 == 'present'
          cd module2
          mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}